name: EcoPower
author: TheBusyBiscuit
description: A Slimefun Addon that focuses on renewable and climate-friendly power generation
main: io.github.thebusybiscuit.ecopower.EcoPowerPlugin
website: https://github.com/TheBusyBiscuit/EcoPower

depend: [Slimefun]

version: ${project.version}
api-version: 1.14
